# .rubocop.yml
#
# Configuration for rubocop, a static code analyzer for Ruby.
#
# https://github.com/bbatsov/rubocop#configuration

inherit_from: .rubocop_todo.yml

# Layout/AccessModifierIndentation
#
# Indent access modifiers like `protected` and `private`.
Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

# Layout/IndentationConsistency
#
# Use Rails-style access modifier indentation.
#
# Example:
# ```
# class Foo
#   def bar
#     puts 'bar'
#   end
#
#   private
#
#     def baz
#       puts 'baz'
#     end
# end
# ```
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

# Naming/FileName
#
# Long, long ago, this was named with a dash rather than an underscore. Now
# it's unconventional, but let's consider it retro and leave it for now so we
# don't have to rename the gem. TODO: Rename using an underscore.
Naming/FileName:
  Exclude:
    - 'lib/pandoc-ruby.rb'


# TODO: Remove when Rubocop hits version 1.0.
Style/HashEachMethods:
  Enabled: true

# TODO: Remove when Rubocop hits version 1.0.
Style/HashTransformKeys:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

# TODO: Remove when Rubocop hits version 1.0.
Style/HashTransformValues:
  Enabled: true

# Style/SymbolArray
#
# Avoid `%i` syntax so symbols look like symbols.
Style/SymbolArray:
  EnforcedStyle: brackets

# Style/RedundantSelf
#
# Explicit `self` is currently preferred in this project in order to
# better distinguish between accessors and local variables.
Style/RedundantSelf:
  Exclude:
    - 'lib/pandoc-ruby.rb'
